[package]
name = "gview-types-macho"
description = "GView type plugin: Mach-O (thin and fat / universal binaries)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gview-core = { path = "../../../crates/gview-core" }
appcui = { path = "../../../../AppCUI-rs/appcui" }
gview-plugin = { path = "../../../crates/gview-plugin" }
gview-view = { path = "../../../crates/gview-view" }
serde_json = "1"
