[package]
name = "gview-view"
description = "GView view layer: ViewControl, SmartViewer traits, renderers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
appcui = { path = "../../../AppCUI-rs/appcui" }
gview-core = { path = "../gview-core" }
