//! Settings bootstrap (spec `00_APP §1.3`).
//!
//! Ground truth: `GViewCore/src/App/GViewApp.cpp` `ResetConfiguration`
//! (L68–120) and `GViewCore/src/App/Instance.cpp` `Init` (L148–204) /
//! `LoadSettings` (L88–126).
//!
//! `gview.ini` sits next to the executable (C++
//! `AppCUI::Application::GetAppSettingsFile()`). Boot order:
//!
//! 1. [`settings_path`] resolves the file;
//! 2. a missing file is generated by [`reset_configuration`] and the
//!    run continues with the defaults;
//! 3. an unusable file (unreadable, oversized, or containing no
//!    sections — C++ `CHECK(ini->GetSectionsCount() > 0)`) is renamed
//!    to `gview.ini.bak`, regenerated, and [`ERR_INVALID_CONFIG`] is
//!    queued as a warning for the desktop to show;
//! 4. otherwise the cache size and key bindings are read.
//!
//! Failing to *write* the file is never fatal: the application starts
//! with the defaults and records a warning, so a read-only install
//! directory still runs.
//!
//! # C++ parity notes
//!
//! - **The cache size is written under one key and read under
//!   another** — quirk #8, see [`KEY_CACHE_SIZE_WRITE`] /
//!   [`KEY_CACHE_SIZE_READ`].
//! - **Seven key bindings are read but only six are written.**
//!   `ResetConfiguration`'s `localKeys` array has six entries while
//!   `Internal.hpp:514` `GViewCommands`, which `LoadSettings` walks,
//!   adds `INSTANCE_ANALYSIS_ENGINE`. `Key.AnalysisEngine` therefore
//!   never appears in a generated file and always falls back to its
//!   default. Replicated by [`WRITTEN_KEY_COMMANDS`] and
//!   [`READ_KEY_COMMANDS`].
//! - The C++ function also refreshes the `AppCUI`, `View.*` and
//!   `AnalysisEngine` sections. Those subsystems have no Rust port
//!   yet, so this writer emits the `[GView]` section and the plugin
//!   sections only; [`update_configuration`] preserves any other
//!   section it finds.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use appcui::input::{Key, KeyCode, KeyModifier};
use gview_core::config::{CacheSize, Config, ConfigError};
use gview_core::constants::DEFAULT_CACHE_SIZE;
use gview_plugin::generic_plugin::GenericPluginMetadata;
use gview_plugin::ini_emit::{key_to_string, EmitOptions};
use gview_plugin::type_plugin::{PluginMetadata, TypePluginRegistry};

use crate::error::AppError;
use crate::file_window::events::{
    KeyboardControl, FILE_WINDOW_COMMAND_FIND, INSTANCE_ANALYSIS_ENGINE, INSTANCE_CHANGE_VIEW,
    INSTANCE_CHOOSE_TYPE, INSTANCE_COMMAND_GOTO, INSTANCE_KEY_CONFIGURATOR,
    INSTANCE_SWITCH_TO_VIEW,
};

/// Name of the settings file (`AppCUI` derives it from the executable
/// name; the C++ build ships `gview.ini`).
pub const SETTINGS_FILE_NAME: &str = "gview.ini";

/// Extension the previous file is renamed to when it cannot be used.
pub const BACKUP_FILE_NAME: &str = "gview.ini.bak";

/// The instance settings section.
pub const GVIEW_SECTION: &str = "GView";

/// Key `ResetConfiguration` **writes** (`ini["GView"]["CacheSize"]`).
pub const KEY_CACHE_SIZE_WRITE: &str = "CacheSize";

/// Key `LoadSettings` **reads**
/// (`sect.GetValue("Config.CacheSize")`). Quirk #8.
pub const KEY_CACHE_SIZE_READ: &str = "Config.CacheSize";

/// Prefix of a key-binding entry (`keyCommand.SetFormat("Key.%s", …)`).
pub const KEY_BINDING_PREFIX: &str = "Key.";

/// C++ `Instance::Init`, shown after a bad configuration is renamed.
pub const ERR_INVALID_CONFIG: &str = "Found an invalid configuration, it will be renamed as \".ini.bak\". Will generated a new one! Please restart GView.";

/// The six bindings `ResetConfiguration` writes, in C++ array order.
pub const WRITTEN_KEY_COMMANDS: [KeyboardControl; 6] = [
    INSTANCE_CHANGE_VIEW,
    INSTANCE_SWITCH_TO_VIEW,
    INSTANCE_COMMAND_GOTO,
    FILE_WINDOW_COMMAND_FIND,
    INSTANCE_CHOOSE_TYPE,
    INSTANCE_KEY_CONFIGURATOR,
];

/// The seven bindings `LoadSettings` reads (`GViewCommands`,
/// `Internal.hpp:514`) — the written six plus the analysis engine.
pub const READ_KEY_COMMANDS: [KeyboardControl; 7] = [
    INSTANCE_CHANGE_VIEW,
    INSTANCE_SWITCH_TO_VIEW,
    INSTANCE_COMMAND_GOTO,
    FILE_WINDOW_COMMAND_FIND,
    INSTANCE_CHOOSE_TYPE,
    INSTANCE_KEY_CONFIGURATOR,
    INSTANCE_ANALYSIS_ENGINE,
];

/// Instance settings after boot.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Settings {
    /// Path the settings were read from (or would be written to).
    pub path: PathBuf,
    /// `defaultCacheSize`, already clamped.
    pub cache_size: CacheSize,
    /// Effective bindings for [`READ_KEY_COMMANDS`], in that order.
    pub keys: Vec<(&'static str, Key)>,
    /// Non-fatal problems to surface once the UI is up.
    pub warnings: Vec<String>,
}

impl Settings {
    /// Defaults for `path`, with no warnings.
    #[must_use]
    pub fn defaults_for(path: PathBuf) -> Self {
        Self {
            path,
            cache_size: CacheSize::clamped(DEFAULT_CACHE_SIZE),
            keys: READ_KEY_COMMANDS
                .iter()
                .map(|control| (control.caption, control.key))
                .collect(),
            warnings: Vec::new(),
        }
    }

    /// Binding for a command caption, if present.
    #[must_use]
    pub fn key(&self, caption: &str) -> Option<Key> {
        self.keys
            .iter()
            .find(|(name, _)| *name == caption)
            .map(|(_, key)| *key)
    }
}

/// `gview.ini` next to the running executable.
///
/// # Errors
///
/// [`AppError::Io`] when the executable path cannot be determined.
pub fn settings_path() -> Result<PathBuf, AppError> {
    let exe = std::env::current_exe()
        .map_err(|e| AppError::io("cannot locate the running executable", e))?;
    Ok(exe.with_file_name(SETTINGS_FILE_NAME))
}

/// Minimal INI scan matching `gview_core::config`: `;` and `#` start
/// comments, names compare case-insensitively.
fn ini_lookup<'a>(text: &'a str, section: &str, key: &str) -> Option<&'a str> {
    let mut in_section = false;
    for raw_line in text.lines() {
        let line = raw_line
            .split_once([';', '#'])
            .map_or(raw_line, |(before, _)| before)
            .trim();
        if line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            in_section = name.trim().eq_ignore_ascii_case(section);
            continue;
        }
        if !in_section {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            if k.trim().eq_ignore_ascii_case(key) {
                return Some(v.trim());
            }
        }
    }
    None
}

/// Every section name in `text`, in file order.
#[must_use]
pub fn section_names(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    for raw_line in text.lines() {
        let line = raw_line
            .split_once([';', '#'])
            .map_or(raw_line, |(before, _)| before)
            .trim();
        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            names.push(name.trim().to_owned());
        }
    }
    names
}

/// Decimal or `0x`-prefixed hexadecimal `u32`.
fn parse_u32(value: &str) -> Option<u32> {
    let value = value.trim();
    let hex = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"));
    hex.map_or_else(|| value.parse().ok(), |h| u32::from_str_radix(h, 16).ok())
}

/// C++ `String::ToKey(default)`: inverts `KeyUtils::ToString`, which
/// renders `<modifier prefix><key name>` (e.g. `Ctrl+Alt+F1`).
///
/// The modifier and key tables are read back out of `AppCUI` rather
/// than transcribed, so the two directions cannot drift apart.
#[must_use]
pub fn parse_key(text: &str) -> Option<Key> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return None;
    }
    // Longest matching modifier prefix wins; index 0 renders as "",
    // which every string trivially starts with.
    let mut best: Option<(usize, KeyModifier)> = None;
    for raw in 0_u8..8 {
        let modifier = KeyModifier::from(raw);
        let prefix = modifier.name();
        let Some(head) = trimmed.get(..prefix.len()) else {
            continue;
        };
        if !head.eq_ignore_ascii_case(prefix) {
            continue;
        }
        if best.is_none_or(|(len, _)| prefix.len() > len) {
            best = Some((prefix.len(), modifier));
        }
    }
    let (prefix_len, modifier) = best?;
    let name = trimmed.get(prefix_len..)?;
    if name.is_empty() {
        return None;
    }
    for raw in 1_u8..64 {
        let code = KeyCode::from(raw);
        if code.name().eq_ignore_ascii_case(name) {
            return Some(Key { code, modifier });
        }
    }
    None
}

/// The `[GView]` section C++ `ResetConfiguration` writes: the cache
/// size then the six key bindings.
#[must_use]
pub fn render_gview_section() -> String {
    let mut out = format!("\n[{GVIEW_SECTION}]\n");
    // `write!` into a `String` cannot fail; the results are discarded
    // deliberately (`clippy::format_push_string`).
    let _ = writeln!(out, "{KEY_CACHE_SIZE_WRITE} = {DEFAULT_CACHE_SIZE}");
    for control in &WRITTEN_KEY_COMMANDS {
        let _ = writeln!(
            out,
            "{KEY_BINDING_PREFIX}{} = {}",
            control.caption,
            key_to_string(control.key)
        );
    }
    out
}

/// The full generated file: the instance section followed by one
/// section per registered plugin.
#[must_use]
pub fn render_configuration(
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
) -> String {
    let mut out = render_gview_section();
    out.push_str(&gview_plugin::ini_emit::emit_plugin_sections(
        types.iter().map(|(name, meta)| (*name, meta)),
        generics.iter().map(|(name, meta)| (*name, meta)),
        EmitOptions::default(),
    ));
    out
}

/// C++ `GView::App::ResetConfiguration`: regenerates the whole file.
///
/// # Errors
///
/// [`AppError::Io`] when the file cannot be written.
pub fn reset_configuration(
    path: &Path,
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
) -> Result<(), AppError> {
    let text = render_configuration(types, generics);
    std::fs::write(path, text).map_err(|e| AppError::io("cannot write the configuration file", e))
}

/// Adds sections that are missing, preserving everything already in
/// the file (the `updateConfig` command).
///
/// Returns `true` when the file was rewritten.
///
/// # Errors
///
/// [`AppError::Io`] when the file cannot be read or written.
pub fn update_configuration(
    path: &Path,
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
) -> Result<bool, AppError> {
    let existing = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            reset_configuration(path, types, generics)?;
            return Ok(true);
        }
        Err(e) => return Err(AppError::io("cannot read the configuration file", e)),
    };
    let present = section_names(&existing);
    let has = |name: &str| present.iter().any(|s| s.eq_ignore_ascii_case(name));

    let mut additions = String::new();
    if !has(GVIEW_SECTION) {
        additions.push_str(&render_gview_section());
    }
    let missing_types: Vec<(&str, &PluginMetadata)> = types
        .iter()
        .filter(|(name, _)| !has(&format!("Type.{name}")))
        .map(|(name, meta)| (*name, meta))
        .collect();
    let missing_generics: Vec<(&str, &GenericPluginMetadata)> = generics
        .iter()
        .filter(|(name, _)| !has(&format!("Generic.{name}")))
        .map(|(name, meta)| (*name, meta))
        .collect();
    additions.push_str(&gview_plugin::ini_emit::emit_plugin_sections(
        missing_types,
        missing_generics,
        EmitOptions::default(),
    ));

    if additions.is_empty() {
        return Ok(false);
    }
    let mut text = existing;
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&additions);
    std::fs::write(path, text)
        .map_err(|e| AppError::io("cannot write the configuration file", e))?;
    Ok(true)
}

/// Reads the settings, regenerating the file when it is missing or
/// unusable (C++ `Instance::Init` + `LoadSettings`).
///
/// Write failures become [`Settings::warnings`] rather than errors, so
/// a read-only install directory still boots.
#[must_use]
pub fn load_or_reset_at(
    path: &Path,
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
) -> Settings {
    let mut settings = Settings::defaults_for(path.to_path_buf());

    let text = match read_settings(path) {
        Ok(Some(text)) => Some(text),
        // No file at all: generate one and continue with defaults.
        Ok(None) => {
            regenerate(path, types, generics, &mut settings);
            None
        }
        // Present but unusable: back it up, regenerate, warn.
        Err(source) => {
            settings.warnings.push(format!(
                "{ERR_INVALID_CONFIG} ({})",
                AppError::config(path.to_path_buf(), source)
            ));
            back_up(path, &mut settings);
            regenerate(path, types, generics, &mut settings);
            None
        }
    };

    let Some(text) = text else {
        return settings;
    };

    // C++ `CHECK(ini->GetSectionsCount() > 0, false, "")`.
    if section_names(&text).is_empty() {
        settings.warnings.push(String::from(ERR_INVALID_CONFIG));
        back_up(path, &mut settings);
        regenerate(path, types, generics, &mut settings);
        return settings;
    }

    settings.cache_size = read_cache_size(&text);
    settings.keys = READ_KEY_COMMANDS
        .iter()
        .map(|control| {
            let entry = format!("{KEY_BINDING_PREFIX}{}", control.caption);
            let key = ini_lookup(&text, GVIEW_SECTION, &entry)
                .and_then(parse_key)
                .unwrap_or(control.key);
            (control.caption, key)
        })
        .collect();
    settings
}

/// [`load_or_reset_at`] on the path from [`settings_path`].
///
/// # Errors
///
/// [`AppError::Io`] when the executable path cannot be determined.
pub fn load_or_reset(
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
) -> Result<Settings, AppError> {
    let path = settings_path()?;
    Ok(load_or_reset_at(&path, types, generics))
}

/// `Ok(None)` when the file does not exist, `Err` when it exists but
/// cannot be used.
fn read_settings(path: &Path) -> Result<Option<String>, ConfigError> {
    match Config::load_from_file(path) {
        // `Config` validated size and encoding; re-read for the text.
        Ok(_) => std::fs::read_to_string(path)
            .map(Some)
            .map_err(ConfigError::Io),
        Err(ConfigError::Io(e)) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e),
    }
}

/// C++ reads `Config.CacheSize`; the generator writes `CacheSize`.
/// Both are accepted, the documented read key first (quirk #8).
fn read_cache_size(text: &str) -> CacheSize {
    let raw = ini_lookup(text, GVIEW_SECTION, KEY_CACHE_SIZE_READ)
        .and_then(parse_u32)
        .or_else(|| ini_lookup(text, GVIEW_SECTION, KEY_CACHE_SIZE_WRITE).and_then(parse_u32))
        .unwrap_or(DEFAULT_CACHE_SIZE);
    CacheSize::clamped(raw)
}

fn back_up(path: &Path, settings: &mut Settings) {
    let backup = path.with_file_name(BACKUP_FILE_NAME);
    if let Err(e) = std::fs::rename(path, &backup) {
        settings.warnings.push(format!(
            "cannot rename the invalid configuration to {}: {e}",
            backup.display()
        ));
    }
}

fn regenerate(
    path: &Path,
    types: &[(&str, PluginMetadata)],
    generics: &[(&str, GenericPluginMetadata)],
    settings: &mut Settings,
) {
    if let Err(e) = reset_configuration(path, types, generics) {
        settings.warnings.push(e.to_string());
    }
}

/// C++ `ListTypes()` in `GView.cpp`: a count line then one padded
/// `name` / `description` row per registered type plugin.
#[must_use]
pub fn list_types(registry: &TypePluginRegistry) -> String {
    let plugins = registry.plugins();
    let mut out = format!("Types : {}\n", plugins.len());
    for plugin in plugins {
        // C++ `std::setw(15) << std::left`.
        let _ = writeln!(out, " {:<15}{}", plugin.name(), plugin.metadata().description);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use appcui::input::{KeyCode, KeyModifier};
    use gview_core::constants::MIN_CACHE_SIZE;
    use gview_plugin::type_plugin::{CommandDef, Pattern, TypePlugin};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(tag: &str) -> Self {
            let base = std::env::temp_dir().join(format!(
                "gview-settings-{}-{tag}-{:?}",
                std::process::id(),
                std::thread::current().id()
            ));
            let _ = std::fs::remove_dir_all(&base);
            std::fs::create_dir_all(&base).expect("create temp dir");
            Self(base)
        }
        fn path(&self, name: &str) -> PathBuf {
            self.0.join(name)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn pe_metadata() -> PluginMetadata {
        PluginMetadata {
            pattern: vec![Pattern::Magic(vec![0x4D, 0x5A])],
            priority: 1,
            description: String::from("Portable executable format for Windows OS binaries"),
            extensions: Vec::new(),
            commands: vec![CommandDef::new(
                "DigitalSignature",
                Key {
                    code: KeyCode::F8,
                    modifier: KeyModifier::Alt,
                },
                "Digital signature",
                1,
            )],
            opcodes_mask: Some(u32::MAX),
        }
    }

    fn hashes_metadata() -> GenericPluginMetadata {
        GenericPluginMetadata {
            description: String::from("Compute hashes over the object"),
            commands: vec![CommandDef::new(
                "Hashes",
                Key {
                    code: KeyCode::F9,
                    modifier: KeyModifier::Alt,
                },
                "Compute hashes",
                1,
            )],
        }
    }

    type TypeMeta = Vec<(&'static str, PluginMetadata)>;
    type GenericMeta = Vec<(&'static str, GenericPluginMetadata)>;

    fn plugins() -> (TypeMeta, GenericMeta) {
        (
            vec![("PE", pe_metadata())],
            vec![("Hashes", hashes_metadata())],
        )
    }

    #[test]
    fn settings_path_sits_next_to_the_executable() {
        let path = settings_path().expect("current exe");
        assert_eq!(path.file_name().and_then(|n| n.to_str()), Some("gview.ini"));
        let exe = std::env::current_exe().expect("current exe");
        assert_eq!(path.parent(), exe.parent());
    }

    #[test]
    fn a_missing_file_is_generated_with_every_expected_entry() {
        let dir = TempDir::new("missing");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();

        let settings = load_or_reset_at(&path, &types, &generics);
        assert!(settings.warnings.is_empty(), "{:?}", settings.warnings);
        assert_eq!(settings.cache_size.get(), DEFAULT_CACHE_SIZE);
        assert!(path.exists(), "the file must be generated");

        let text = std::fs::read_to_string(&path).expect("read back");
        assert!(text.contains("[GView]"), "{text}");
        assert!(text.contains("CacheSize = 10485760"), "{text}");
        // Exactly the six keys `ResetConfiguration` writes.
        let written = text.matches("Key.").count();
        assert_eq!(written, WRITTEN_KEY_COMMANDS.len(), "{text}");
        for control in &WRITTEN_KEY_COMMANDS {
            assert!(text.contains(&format!("Key.{}", control.caption)), "{text}");
        }
        // One section per plugin.
        assert!(text.contains("[Type.PE]"), "{text}");
        assert!(text.contains("[Generic.Hashes]"), "{text}");
        let sections = section_names(&text);
        assert_eq!(sections.len(), 3, "{sections:?}");
    }

    #[test]
    fn the_generated_file_reloads_to_the_same_settings() {
        let dir = TempDir::new("roundtrip");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        let first = load_or_reset_at(&path, &types, &generics);
        let second = load_or_reset_at(&path, &types, &generics);
        assert_eq!(first.cache_size, second.cache_size);
        assert_eq!(first.keys, second.keys);
        assert!(second.warnings.is_empty(), "{:?}", second.warnings);
    }

    #[test]
    fn a_file_without_sections_is_backed_up_and_regenerated() {
        let dir = TempDir::new("invalid");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "not an ini file\njust text\n").expect("seed");

        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(
            settings.warnings.first().map(String::as_str),
            Some(ERR_INVALID_CONFIG),
            "the C++ wording must be surfaced verbatim"
        );
        let backup = dir.path(BACKUP_FILE_NAME);
        assert!(backup.exists(), "the old file must be preserved");
        assert_eq!(
            std::fs::read_to_string(&backup).expect("backup"),
            "not an ini file\njust text\n"
        );
        let text = std::fs::read_to_string(&path).expect("regenerated");
        assert!(text.contains("[GView]"), "{text}");
    }

    #[test]
    fn an_oversized_file_is_reported_and_regenerated() {
        let dir = TempDir::new("oversized");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        let big = vec![b'x'; (gview_core::config::MAX_CONFIG_FILE_SIZE + 1) as usize];
        std::fs::write(&path, big).expect("seed");

        let settings = load_or_reset_at(&path, &types, &generics);
        assert!(
            settings
                .warnings
                .first()
                .is_some_and(|w| w.starts_with(ERR_INVALID_CONFIG)),
            "{:?}",
            settings.warnings
        );
        assert!(dir.path(BACKUP_FILE_NAME).exists());
        assert_eq!(settings.cache_size.get(), DEFAULT_CACHE_SIZE);
    }

    #[test]
    fn a_small_cache_size_is_clamped_to_the_minimum() {
        let dir = TempDir::new("clamp");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "[GView]\nConfig.CacheSize = 65535\n").expect("seed");
        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(settings.cache_size.get(), MIN_CACHE_SIZE);
        assert!(settings.warnings.is_empty(), "{:?}", settings.warnings);
    }

    #[test]
    fn a_huge_cache_size_is_clamped_to_the_maximum() {
        let dir = TempDir::new("clamp-max");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "[GView]\nConfig.CacheSize = 0xFFFFFFFF\n").expect("seed");
        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(
            settings.cache_size.get(),
            gview_core::constants::MAX_CACHE_SIZE
        );
    }

    #[test]
    fn an_unwritable_location_warns_instead_of_panicking() {
        let dir = TempDir::new("readonly");
        // A regular file standing in for the directory makes every
        // write fail portably.
        let blocker = dir.path("blocker");
        std::fs::write(&blocker, b"x").expect("seed");
        let path = blocker.join("gview.ini");
        let (types, generics) = plugins();

        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(settings.cache_size.get(), DEFAULT_CACHE_SIZE);
        assert_eq!(
            settings.keys.len(),
            READ_KEY_COMMANDS.len(),
            "defaults must still be available"
        );
        assert!(
            settings
                .warnings
                .iter()
                .any(|w| w.contains("cannot write the configuration file")),
            "{:?}",
            settings.warnings
        );
    }

    #[test]
    fn key_bindings_round_trip_through_the_file() {
        for control in &READ_KEY_COMMANDS {
            let rendered = key_to_string(control.key);
            assert_eq!(
                parse_key(&rendered),
                Some(control.key),
                "{} rendered as {rendered:?}",
                control.caption
            );
        }
    }

    #[test]
    fn parse_key_handles_every_modifier_combination() {
        for raw in 0_u8..8 {
            let key = Key {
                code: KeyCode::F1,
                modifier: KeyModifier::from(raw),
            };
            assert_eq!(parse_key(&key_to_string(key)), Some(key));
        }
        assert_eq!(
            parse_key("ctrl+alt+f1"),
            Some(Key {
                code: KeyCode::F1,
                modifier: KeyModifier::Ctrl | KeyModifier::Alt,
            }),
            "C++ ToKey is case-insensitive"
        );
    }

    #[test]
    fn parse_key_rejects_garbage_without_panicking() {
        for text in ["", "   ", "Ctrl+", "NotAKey", "Ctrl+NotAKey", "+", "Ctrl++"] {
            assert_eq!(parse_key(text), None, "for {text:?}");
        }
    }

    #[test]
    fn a_custom_key_binding_overrides_the_default() {
        let dir = TempDir::new("keys");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "[GView]\nKey.ChangeView = Ctrl+F9\n").expect("seed");
        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(
            settings.key("ChangeView"),
            Some(Key {
                code: KeyCode::F9,
                modifier: KeyModifier::Ctrl,
            })
        );
        // Unlisted bindings keep their defaults.
        assert_eq!(
            settings.key("ShowKeys"),
            Some(INSTANCE_KEY_CONFIGURATOR.key)
        );
    }

    #[test]
    fn an_unparsable_key_keeps_the_default() {
        let dir = TempDir::new("badkey");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "[GView]\nKey.ChangeView = NotAKey\n").expect("seed");
        let settings = load_or_reset_at(&path, &types, &generics);
        assert_eq!(settings.key("ChangeView"), Some(INSTANCE_CHANGE_VIEW.key));
    }

    #[test]
    fn update_configuration_adds_only_missing_sections() {
        let dir = TempDir::new("update");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        std::fs::write(&path, "[GView]\nCacheSize = 1048576\n\n[Type.PE]\nPriority = 7\n")
            .expect("seed");

        assert!(update_configuration(&path, &types, &generics).expect("update"));
        let text = std::fs::read_to_string(&path).expect("read back");
        // Existing content preserved verbatim.
        assert!(text.contains("CacheSize = 1048576"), "{text}");
        assert!(text.contains("Priority = 7"), "{text}");
        // The one missing section was appended, the present ones not
        // duplicated.
        assert_eq!(text.matches("[Type.PE]").count(), 1, "{text}");
        assert_eq!(text.matches("[GView]").count(), 1, "{text}");
        assert_eq!(text.matches("[Generic.Hashes]").count(), 1, "{text}");

        // Nothing left to add the second time.
        assert!(!update_configuration(&path, &types, &generics).expect("update"));
    }

    #[test]
    fn update_configuration_creates_a_missing_file() {
        let dir = TempDir::new("update-missing");
        let path = dir.path("gview.ini");
        let (types, generics) = plugins();
        assert!(update_configuration(&path, &types, &generics).expect("update"));
        assert!(path.exists());
        assert!(std::fs::read_to_string(&path)
            .expect("read")
            .contains("[Type.PE]"));
    }

    #[test]
    fn list_types_matches_the_cpp_layout() {
        let mut registry = TypePluginRegistry::new();
        registry
            .register(gview_plugin::type_plugin::TypePluginDescriptor {
                name: "PE",
                validate: |_, _| true,
                create_instance: || {
                    gview_plugin::default_type::DefaultTypePlugin::create_instance()
                        as Box<dyn TypePlugin>
                },
                metadata: pe_metadata,
            })
            .expect("register");

        let text = list_types(&registry);
        let mut lines = text.lines();
        assert_eq!(lines.next(), Some("Types : 1"));
        assert_eq!(
            lines.next(),
            Some(" PE             Portable executable format for Windows OS binaries"),
            "name padded to 15 columns after one leading space"
        );
        assert_eq!(lines.next(), None);
    }

    #[test]
    fn list_types_on_an_empty_registry() {
        let registry = TypePluginRegistry::new();
        assert_eq!(list_types(&registry), "Types : 0\n");
    }
}
