[package]
name = "gview-app"
description = "GView terminal binary-analysis application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gview"
path = "src/main.rs"

[dependencies]
appcui = { path = "../../../AppCUI-rs/appcui" }
gview-core = { path = "../gview-core" }
gview-view = { path = "../gview-view" }
gview-plugin = { path = "../gview-plugin" }
regex = "1"
serde_json = "1"
