macro(add_windows_resource executableName resourceFileName)
    if (MSVC AND DEFINED GVIEW_RESOURCE_FILE_TEMPLATE)
        set(GVIEW_RESOURCE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${resourceFileName}")
        message("Setting version to ${GVIEW_RESOURCE_FILE}")
        set(EXECUTABLE_NAME "${executableName}")
        configure_file(${GVIEW_RESOURCE_FILE_TEMPLATE} ${GVIEW_RESOURCE_FILE} @ONLY)
        target_sources(${PROJECT_NAME} PRIVATE ${GVIEW_RESOURCE_FILE})
    endif()
endmacro()
